# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

queue:
  name: 'Hosted VS2017'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'
name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    configuration: 'release'
    packagesToPack: 'src/core/pactifier.csproj'
    versioningScheme: byBuildNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
# Push NuGet packages.
- task: NuGetCommand@2
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    publishFeedCredentials: 'Nuget-as-olav'
